### ISSUE TITLE
Consider removing Aruco and Tango capability, focusing on artoolkit

### ISSUE THREAD

**Issue by lcb931023** [HeliosInteractive/AR.js#4]
The library bundles aruco, three.webar.js for tango, and artoolkit together; yet most examples only use artoolkit.

Should we remove Aruco and Tango support? This would reduce library size, simplify usage, and let us focus development on supporting artoolkit.

**Comment by mneil** [comment]
Tango will be deprecated March 1st this year. I would think that means it's safe to pull out any support for tango moving forward.

**Comment by lcb931023** [comment]
Tango is purged. Aruco remains, but now we have an additional lean build that doesn't include aruco. https://github.com/HeliosInteractive/AR.js/commit/4bfbf4df00acdc6d981dc47ea08e4904c013c00c

**Comment by lcb931023** [comment]
As a side note - while the lean build is smaller, it is still close to 1MB in size. The bottleneck is jsartoolkit and its api - these two alone is 839kb.

**Comment by lcb931023** [comment]
https://github.com/freinbichler/ar-room-availability/blob/master/src/js/vendor/aframe-ar.js manages to work at 897kb. This looks like an older ar.js that doesn't include unfinished support for aruco / tango.

**Comment by lcb931023** [comment]
Tried out a few demos with Aruco as backend. It does work, though tracking isn't as stable as tango.
